config/routes.rb
Rails.application.routes.draw do
  match '/subscribe', to: 'pages#subscribe', via: 'post'
  match '/contact_us', to: 'pages#contact_us', via: 'post'
  root 'pages#land'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def land
  end

  def contact_us
    name = params[:name]
    email = params[:email]
    phone = params[:phone]
    message = params[:message]
    # mailer send email to admin
    MyMailer.send_email_contact(name, email, phone, message).deliver_now
    redirect_to root_path
  end

  def subscribe
    @list_id = ENV['MAILCHIMP_LIST_ID']
    gb = Gibbon::API.new
    gb.lists.subscribe({
                           id: @list_id,
                           email: {email: params[:sub_email]}
                       })
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Landing Page</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body id="page-top" class="index">

<%= yield %>

<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
</body>
</html>

app/views/pages/_contact_us.html.erb
<!-- Contact Section -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Contact Us</h2>
        <hr class="star-primary">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
        <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
        <%= form_tag(contact_us_path, method: 'post', multipart: true) do %>
          <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= label_tag 'name', 'Name' %>
              <%= text_field_tag 'name', nil, class: 'form-control', placeholder: 'Name' %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= label_tag 'email', 'Email Address' %>
              <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'Email Address' %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= label_tag 'phone', 'Phone Number' %>
              <%= telephone_field_tag 'phone', nil, class: 'form-control', placeholder: 'Phone Number' %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= label_tag 'message', 'Message' %>
              <%= text_area_tag 'message', nil, class: 'form-control', placeholder: 'Message', rows: 5 %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="row">
            <div class="form-group col-xs-12">
              <%= button_tag(type: 'submit', class: 'btn btn-success btn-lg') do %>
                Send Message to Admin
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/pages/_subscribe.html.erb
<div class="col-lg-8 col-lg-offset-2 text-center">
  <hr class="star-light">
  <h3>Subscribe to our mailing list by entering you email</h3>
  <hr class="star-light">
  <%= form_tag(subscribe_path, method: 'post', multipart: true) do %>
    <div class="row control-group">
      <div class="form-group col-xs-12 floating-label-form-group controls">
        <%= label_tag 'sub_email', 'Email Address' %>
        <%= email_field_tag 'sub_email', nil, class: 'form-control', placeholder: 'Email Address' %>
        <p class="help-block text-danger"></p>
      </div>
    </div>
    <br>
    <div id="success"></div>
    <div class="row">
      <div class="form-group col-xs-12">
        <%= button_tag(type: 'submit', class: 'btn btn-primary btn-lg') do %>
            Subscribe
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/land.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top navbar-shrink">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#page-top">CODElit</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
          <a href="#portfolio">Courses</a>
        </li>
        <li class="page-scroll">
          <a href="#about">About</a>
        </li>
        <li class="page-scroll">
          <a href="#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<!-- Header -->
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= image_tag 'profile.jpg', alt: "", class: "img-responsive" %>
        <div class="intro-text">
          <span class="name">CODElit</span>
          <hr class="star-light">
          <span class="skills">Learn by Doing Courses</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Portfolio Grid Section -->
<section id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Courses</h2>
        <hr class="star-primary">
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-eye fa-3x"></i>
            </div>
          </div>
          <%= image_tag 'image1.jpg', alt: "", class: "img-responsive" %>
        </a>
      </div>
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-eye fa-3x"></i>
            </div>
          </div>
          <%= image_tag 'image1.jpg', alt: "", class: "img-responsive" %>
        </a>
      </div>
      <div class="col-sm-4 portfolio-item">
        <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
          <div class="caption">
            <div class="caption-content">
              <i class="fa fa-eye fa-3x"></i>
            </div>
          </div>
          <%= image_tag 'image1.jpg', alt: "", class: "img-responsive" %>
        </a>
      </div>
    </div>
  </div>
</section>

<!-- About Section -->
<section class="success" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>About</h2>
        <hr class="star-light">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-lg-offset-2">
        <p>Code-lit is a coding literature where you learn coding by doing projects from Zero to Professional.</p>
      </div>
      <div class="col-lg-4">
        <p>HTML, CSS, JavaScript, Python, Ruby, Rails, Embedded Systems, C, C++ and many more...</p>
      </div>
      <%= render 'subscribe' %>
    </div>
  </div>
</section>

<%= render 'contact_us' %>

<!-- Footer -->
<footer class="text-center">
  <div class="footer-above">
    <div class="container">
      <div class="row">
        <div class="footer-col col-md-6">
          <h3>Location</h3>
          <p>Via Leonardo Cucito 6/11, Genova, 16145, Italy.<br></p>
        </div>
        <div class="footer-col col-md-6">
          <h3>Around the Web</h3>
          <ul class="list-inline">
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
            </li>
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
            </li>
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
            </li>
            <li>
              <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
            </li>
            <li>
              <a href="http://codelit.com/" class="btn-social btn-outline" target="_blank"><i class="fa fa-fw fa-dribbble"></i></a>
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
  <div class="footer-below">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          Copyright © http://codelit.com 2015
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll visible-xs visible-sm">
  <a class="btn btn-primary" href="#page-top">
    <i class="fa fa-chevron-up"></i>
  </a>
</div>